.nh
.TH "ORTFODB" "1" "Apr 2024" "https://ortfo.org/db" "ortfo/db Manual"

.SH NAME
.PP
ortfodb-exporters-doc - Get help for a specific exporter


.SH SYNOPSIS
.PP
\fBortfodb exporters doc  [flags]\fP


.SH DESCRIPTION
.PP
Get help for a specific exporter


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-c\fP, \fB--config\fP="ortfodb.yaml"
	config file path

.PP
\fB--scattered\fP[=false]
	Operate in scattered mode. In scattered mode, the description.md files are searched inside `.ortfo' folders in every folder of the database directory, instead of directly in the database directory's folders. See https://github.com/ortfo/


.SH EXAMPLE
.EX
$ ortfodb exporters help localize

[1m[34mlocalize  [0m  Export separately the database as a single database for each language. The `content` field of each work is localized, meaning it's not an object mapping languages to localized content, but the content directly, in the language.
[0m            [1m[36mOptions[0m:
[0m            [1m[2m•[0m [34mfilename_template[0m 
[0m

To add [1mlocalize[0m to your project, add the following to [36myour ortfodb config file[0m:

[0m  [1m[2m[31mexporters:
[0m    [1m[31mlocalize:[0m [2m# <- add this alongside your potential other exporters
[0m      [1m[31mfilename_template:[0m [32m""[0m
[0m
Feel free to change these configuration values. Check out the exporter's documentation to learn more about what they do.


.EE


.SH SEE ALSO
.PP
\fBortfodb-exporters(1)\fP


.SH HISTORY
.PP
17-Apr-2024 Auto generated by spf13/cobra
